// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";

export type CallLambda = {
  other: Identity,
  app: bigint,
  lam: bigint,
  callId: number,
  arg: string,
};

/**
 * A namespace for generated helper functions.
 */
export namespace CallLambda {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("other", AlgebraicType.createIdentityType()),
      new ProductTypeElement("app", AlgebraicType.createU256Type()),
      new ProductTypeElement("lam", AlgebraicType.createU256Type()),
      new ProductTypeElement("callId", AlgebraicType.createU32Type()),
      new ProductTypeElement("arg", AlgebraicType.createStringType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: CallLambda): void {
    CallLambda.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): CallLambda {
    return CallLambda.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

