// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";

export type CallLambda = {
  other: Identity,
  app: bigint,
  lam: bigint,
  arg: string,
};

/**
 * A namespace for generated helper functions.
 */
export namespace CallLambda {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("other", AlgebraicType.createIdentityType()),
      new ProductTypeElement("app", AlgebraicType.createU256Type()),
      new ProductTypeElement("lam", AlgebraicType.createU256Type()),
      new ProductTypeElement("arg", AlgebraicType.createStringType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: CallLambda): void {
    CallLambda.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): CallLambda {
    return CallLambda.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

